sudo: false

language: haskell
ghc: 8.0

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal test --haddock --no-haddock-deps

cache:
  directories:
  - $HOME/.stack

deploy:
  provider: hackage
  username: graknlabs
  password:
    secure: MmKEBH+Coqy4Hv7P7mmRaPLtOwOx4S7krT3biH1hnBuPmrDJ2oMyMUJCqNc+g/Y/pVCK8nSpyQXjOE5Fl2Bncsvu+RrDuuu+6WIj+7Sg4MUrRhT3MTDFppk6VqRLNIkPIy9yJqeS5rL1E9+fqE45/HZi91tkAMhfWs0ct4cywd8JURvwrCUyjijnK0+hNEcx2bfjgl0Suj7JU0BlQcLfpLosiXyV8Q/8fS1FZ1fQGen0baNT8YyXP8/1WI58oVZU3xiwToYtG8S+44STciSE1yzzf914+CKtdxirMKKKzWfkqIZP9VTjFelT6Q2lGiiVgWWYAlMHTp+QClMZzePR7T8i5RvY6t5N9BCM8R3Ob9k66BS2ZCEs39NhwbZBzwKey7OH+MZeOwmFNa5h/kIUFZRF/HGX6e2NF9jfpuGBB6jQnxIJgK956eUWz+g09Gkbr+G9bAgsyUS0HQeOzot8HKmIA/ykZmk8JGhW1Rljw40tJ1qg16jSVxKAsFBwchxANKT0y+RxB/JaIrDrie6Ova11ZCCIHljMv4Zk/oIIrJqIgJ5F2S54b6m3cR5Z/15zu2M+eV+gm0l+mVdsGeldGP5lKPZ49BmMP5VP0ZG0mXr5kLd6S1SG5cXWn/6wDM0VcuaQSWp0t/NeoNZrT/VmFz9pIK123Y4iPx1pvyrWBmU=
  on:
    repo: graknlabs/grakn-haskell
